/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as PaymentOtherRouteImport } from './routes/payment-other'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutMethodRouteImport } from './routes/checkout.method'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentOtherRoute = PaymentOtherRouteImport.update({
  id: '/payment-other',
  path: '/payment-other',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutMethodRoute = CheckoutMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/index': typeof Char91indexChar93Route
  '/order-confirmed': typeof OrderConfirmedRoute
  '/payment-other': typeof PaymentOtherRoute
  '/checkout/method': typeof CheckoutMethodRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/product/$id': typeof ProductIdRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/index': typeof Char91indexChar93Route
  '/order-confirmed': typeof OrderConfirmedRoute
  '/payment-other': typeof PaymentOtherRoute
  '/checkout/method': typeof CheckoutMethodRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/product/$id': typeof ProductIdRoute
  '/checkout': typeof CheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/index': typeof Char91indexChar93Route
  '/order-confirmed': typeof OrderConfirmedRoute
  '/payment-other': typeof PaymentOtherRoute
  '/checkout/method': typeof CheckoutMethodRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/product/$id': typeof ProductIdRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/index'
    | '/order-confirmed'
    | '/payment-other'
    | '/checkout/method'
    | '/checkout/payment'
    | '/product/$id'
    | '/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/index'
    | '/order-confirmed'
    | '/payment-other'
    | '/checkout/method'
    | '/checkout/payment'
    | '/product/$id'
    | '/checkout'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/index'
    | '/order-confirmed'
    | '/payment-other'
    | '/checkout/method'
    | '/checkout/payment'
    | '/product/$id'
    | '/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  Char91indexChar93Route: typeof Char91indexChar93Route
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PaymentOtherRoute: typeof PaymentOtherRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-other': {
      id: '/payment-other'
      path: '/payment-other'
      fullPath: '/payment-other'
      preLoaderRoute: typeof PaymentOtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/method': {
      id: '/checkout/method'
      path: '/method'
      fullPath: '/checkout/method'
      preLoaderRoute: typeof CheckoutMethodRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutMethodRoute: typeof CheckoutMethodRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutMethodRoute: CheckoutMethodRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  Char91indexChar93Route: Char91indexChar93Route,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PaymentOtherRoute: PaymentOtherRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
